name: "TimeSloth"
version: "0.1.1.6"
slug: "timesloth"
description: "Professional Time Tracking for Sloths."
arch:
  - aarch64
init: false
options:
  secret_key: "CHANGE_ME_IN_ADDON_CONFIG"
  db_folder: "/data"
schema:
  secret_key: "password"
  db_folder: "str"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web Interface"