name: "TimeSloth"
version: "2.0.0"
slug: "timesloth"
description: "Professional Time Tracking for Sloths ðŸ¦¥"
url: "https://github.com/StefanZug/timesloth"
# Wichtig: Kleinschreibung deines Usernamens beachten!
image: "ghcr.io/stefanzug/timesloth-{arch}"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8080
panel_icon: mdi:sloth
ingress_entry: /
ports:
  8080/tcp: 8080
map:
  - config:rw
  - ssl:ro
options: {}
schema: {}