name: "TimeSloth"
version: "0.1.9.12"
slug: "timesloth"
description: "Professional Time Tracking for Sloths."
url: "https://github.com/StefanZug/timesloth"
arch:
  - aarch64
init: false
map:
  - ssl
options:
  secret_key: "CHANGE_ME_IN_ADDON_CONFIG"
  db_folder: "/data"
  ssl: true
  certfile: "fullchain.pem"
  keyfile: "privkey.pem"
schema:
  secret_key: "password"
  db_folder: "str"
  ssl: "bool"
  certfile: "str"
  keyfile: "str"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web Interface"