name: "TimeSloth"
version: "0.0.20.2"
slug: "timesloth"
description: "Professional Time Tracking for Sloths."
arch:
  - armv7
  - aarch64
  - amd64
init: false
options:
  secret_key: "CHANGE_ME_IN_ADDON_CONFIG"
  db_folder: "/data"
  redis_url: "redis://core-redis:6379/0"
schema:
  secret_key: "password"
  db_folder: "str"
  redis_url: "str"
webui: "http://[HOST]:[PORT:8080]"
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "Web Interface"