name: Build and Publish Add-on

on:
  push:
    branches:
      - "main"

jobs:
  build:
    name: "Build Add-on"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Build the add-on"
        uses: "home-assistant/builder@master"
        with:
          # Baut alle in config.yaml definierten Architekturen
          args: |
            --all \
            --target .
          # Aktiviert das Docker-Layer-Caching, um Builds zu beschleunigen
          cache: true
          # Token zum Pushen des Images zur GitHub Container Registry (ghcr.io)
          github_token: ${{ secrets.GITHUB_TOKEN }}